CATEGORIA_FATURA_CARTAO = "Fatura de Cartao"
CATEGORIA_FATURA_CARTAO_SEM_ACENTO = "Fatura de Cartao"
CATEGORIA_TRANSFERENCIA = "Transferencia"
CATEGORIAS_OCULTAS_CADASTRO = []
CATEGORIAS_OCULTAS_LANCAMENTO = []
CATEGORIAS_TECNICAS = []
